export const ErrorCode = {
  SERVER_ERROR: 'SERVER_ERROR',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  GOOGLE_AUTHENTICATION_FAIL: 'GOOGLE_AUTHENTICATION_FAIL',
  USER_EXISTED: 'USER_EXISTED',
  ERROR_GENERATING_TOKEN: 'ERROR_GENERATING_TOKEN',
  ERROR_ENCODING_TOKEN: 'ERROR_ENCODING_TOKEN',
  ERROR_VERIFYING_TOKEN: 'ERROR_VERIFYING_TOKEN',
  NOT_FOUND_MENTOR: 'NOT_FOUND_MENTOR',
};
